- hosts: all
  become: yes
  tasks: 
  - name: install packages 
    ansible.builtin.apt:
      name:
        - apache2
        - tree
        - unzip
      state: present
      update_cache: yes


  - name: Start service
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes
