- hosts: all
  become: yes
  tasks: 
  - name: install packages 
    ansible.builtin.apt:
      name: tree
      update_cache: yes 
    register: hello  

  - name: debug mod
    debug: 
      msg: "{{ hello }}"